language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
env:
  global:
  - secure: XJjkeLZjcQKbtAXXnmnX0/8Va7I+R08uZS9+9kC/V51Bf+qfIHuPpwUmQwahi2yvbAgQQXFHDZ22fnsLaSCNr1QUCmSCR4a/bjyyGKYbF0F9dbXabGDJqyOWNXBDjZWQeY5JFG6//skUckHurQl8NUBsZxk0IB3drJhdo44maOPHzeyBeNft30V7E4n0bnbxc+FWkfxxpgX9G56Mjq+59mwh6ev2731XwmyveHFAuWGVU282V3YeR6gaQXkdxf5/DwzH6vNAkzmfRpcIOk6AU9DssB2EMSFnWZXhfWbljQo0bmnEGDzCelDR3cQLdkHN747/cFiH9VXj5lHhiRKcDnq12XXNrlyNUT5Mf69zUIsctCbWV9HRW21I6K1SB79DcelQtfLqlr/FbNeEmZiFnBUewJlhUl9/CqVa72ZUC/besu+YLe60DHQTbz4REde2j52hIc+plo0BNYdz88Yxe0HwHjsigZrF9r2LpT++9S9eQSq8jYoxK3JR5GdntIU+ECza8r5Nvxmc/diPGgpM3IJ0Kofcb9ldIhhUgey5AEketw1lORTu9LLsfUFuFi5eqo2mqqj5y7ThW5Q2m95EsulaEMMLlqKUQap4Slxji4p5lXbcf4BV+EYq01kzmnyrByh+N6kMQeLVsICdvxB7ldTzawzeAX9UCahEhr7DViA=
  - secure: Jfm+BEbXKQUrypsrTpJKMZFftDqpeg8KDvB0G9CwwZG5lf6aveTFWf9d8kkkFWsqmpCjpTd6ICCALRgBWGAaJzywMRgRUwbRSybnpxTKNWlxh2vWrcEioinfGYgGn/xwt3FxmwEn/9k+Lcd0KBluYWBMupr6e8PTQko8qhKQpIpNUk0VkYrL0+ND+qqNwyKvtU4mRJAfD46CxolxbE3QF8PqmoapFA2Nv0WspspmoKEAEHt5ImTszvEF6g2DbPLWJ4pBRybXRS84uMhJnA7q+cLxS7Ml76D+zYK8Xnh3ntLSJQyCIi4mtyVzL2lJ0QhlheOiMnvgmKTtw1rHTpPB7ZIl2yIGOJypFepPXw8vt9ltZjECYmNpagEJ8A3Baq3E+9JtQ0YMx7JOyG+VKJA2JS4eflq8fe8OUJKL4Xy9mfBzg26clkYqAHvg6/qSWChVtGXm5KLANmblY1Bj+Gjh+bf0Kpa26/xaQSCe2z3QFB8ehNVdHIj1E/46TLkhlMdRAs4GFrqDSrnsxET1CY+/FCyv6JB6EYbL+iRzcVrxaV/1VDu3h17Lc3EvUzUZY8C1xPFmrrvXQlyVG/uy6axXecAcmP9cASrrGeSI5CTDMQTuO1gx5qKOKc7W4Belr/Ccp8xuzPVx5QmEYK8nan9aszkwx5VQEzq7U7gSBGfYy2c=
  - COMMIT=${TRAVIS_COMMIT::8}
branches:
  only:
  - master
  - development
script:
- npm run build
- npm test
deploy:
  provider: script
  script: bash scripts/docker_deploy.sh
  on:
    branch: master

